# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66626a67aa3b3230d0f5e27682a6217c3cec772ed5ea93a66f2a1c120003932d5f569cb1f7c4bf130a3e4d48299dae71670f979efd8244748add44442a92285e

test:
  secret_key_base: ae4bdb98e84139a3e664d63272b7b83934c87b632a2b41ef6ee18d88dcd5a4f3e77bb25c0b59f45a7be38ff2938be70f509233b691df4d31b5273c2b37bdb562

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
